# Generated by Django 5.0.3 on 2024-05-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
                ('genre_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_language', models.CharField(max_length=100)),
                ('movie_description', models.TextField(null=True)),
                ('movie_duration', models.CharField(max_length=100)),
                ('movie_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.genre_model')),
            ],
        ),
    ]
